### ISSUE TITLE
Using mullvad _only_ on one VLAN

### ISSUE THREAD

**Issue by q20** [bneijt/mullvad-edgerouter-x#5]
Hi there!

Before jumping in and deploying changes to my er-x, I'd like to check with you what I'd need to change to force a single VLAN to use wg0. Essentially, I want a specific VLAN to route through wg0, all other network traffic is untouched.

I have a VLAN (Vlan ID 30) on switch0.30 with the IP 10.10.30.1/24.

Soooo, I made the following changes to the generated command list:

...
`set destination group address-group NETv4_switch0.30`
...
`set interfaces switch switch0 vif 30 firewall in modify lanInModify`
...

Would this be all that differs from your setup, which forces all clients on switch0 to be routed through wg0?

**Comment by bneijt** [comment]
Sorry for replying so late, I put this on my todo and it kind of stuck there.

I think your assumption is right, the main thing to get the traffic to flow through wireguard is using the modify rule to change the routing table to push everything onto wg.

Given my late reply, you probably tried it already, hope it worked!

**Comment by q20** [comment]
Thanks for the belated response.  : )

I was hoping you'd be able to comment directly on the two lines changed in my initial question, above. Are those two changes correctly formatted the only two changes required to have mullvad used for VLAN ID 30?

Thanks!

**Comment by bneijt** [comment]
Oh, sorry.

Yes, the first line will make sure that traffic coming in from the switch that is targeted at the local network will not be given the wireguard routing table, which is required to allow the devices on that network to still talk to each other.

The second line will make sure the modify firewall is applied.

I have no experience using virtual networks on ubiquity hardware, so I'm not sure whether the syntax is correct.

**Comment by q20** [comment]
OK, thanks for trying!
I'm a little apprehensive applying these sweeping changes to my device... I'll take the plunge after a backup some time.  ; )
